"""empty message

Revision ID: a33a0b2ec053
Revises: 
Create Date: 2022-05-19 14:34:32.336588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a33a0b2ec053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('endereco', sa.JSON(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('pis', sa.String(length=40), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
